//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouLearn.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSG() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouLearn.Domain.Resource.MSG", typeof(MSG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A {0} dever maior ou igual a {1}.
        /// </summary>
        public static string A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados não encontrados.
        /// </summary>
        public static string DADOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este {0} já existe.
        /// </summary>
        public static string ESTE_X0_JA_EXISTE {
            get {
                return ResourceManager.GetString("ESTE_X0_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um {0} chamado {1}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_CHAMADO_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_CHAMADO_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um {0} com a {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_A_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_A_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um {0} com o {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma {0} chamada {1}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_CHAMADA_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_CHAMADA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma {0} com a {1}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_COM_A_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_COM_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possivel excluir uma {0} associada a uma {1}.
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objeto 
        ///Objeto {0} é obrigatório.
        /// </summary>
        public static string OBJETO_X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("OBJETO_X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso.
        /// </summary>
        public static string OPERACAO_REAIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REAIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} inválido.
        /// </summary>
        public static string X0_INVALIDO {
            get {
                return ResourceManager.GetString("X0_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatório e deve conter entre {1} e {2} caracteres.
        /// </summary>
        public static string X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
    }
}
